#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Magic.Droid.Resource", IsApplication=true)]

namespace Magic.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Tesseract.Droid.Resource.String.ApplicationName = global::Magic.Droid.Resource.String.ApplicationName;
			global::Tesseract.Droid.Resource.String.Hello = global::Magic.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int camera_id = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int show_fps = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int test = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int CamControlView = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int MainButtonBlob = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int MainButtonCam = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int MainButtonCameraControl = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int MainButtonImageManipulation = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int MainButtonOCRTest = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int ManipulationView = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int OCRTestButton1 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int OCRTestText = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int any = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int back = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int color_blob_detection_activity_surface_view = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int front = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int surfaceView = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CameraControl = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int color_blob_detection_surface_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ImageManipulation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int OCRTest = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Preview = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
